// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXvs8BAc_DUT7VBaDtNDSPhW564HNL9o',
    appId: '1:743186260255:web:a4c7e1f39a675e47aad02a',
    messagingSenderId: '743186260255',
    projectId: 'bakeryshopproject-f41f9',
    authDomain: 'bakeryshopproject-f41f9.firebaseapp.com',
    storageBucket: 'bakeryshopproject-f41f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9aiZE904sco-Vi7pLOv8v55U2aFhEGEQ',
    appId: '1:743186260255:android:53c7eda425c2b8aeaad02a',
    messagingSenderId: '743186260255',
    projectId: 'bakeryshopproject-f41f9',
    storageBucket: 'bakeryshopproject-f41f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNcE5l2tch9SyJCX8Tt324HwjJWp6YuBk',
    appId: '1:743186260255:ios:c94633ab75213dbcaad02a',
    messagingSenderId: '743186260255',
    projectId: 'bakeryshopproject-f41f9',
    storageBucket: 'bakeryshopproject-f41f9.appspot.com',
    iosClientId:
        '743186260255-30ueqe8cgelr7f38lkncm2msqs2ia6q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakeryshopProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNcE5l2tch9SyJCX8Tt324HwjJWp6YuBk',
    appId: '1:743186260255:ios:c94633ab75213dbcaad02a',
    messagingSenderId: '743186260255',
    projectId: 'bakeryshopproject-f41f9',
    storageBucket: 'bakeryshopproject-f41f9.appspot.com',
    iosClientId:
        '743186260255-30ueqe8cgelr7f38lkncm2msqs2ia6q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakeryshopProject',
  );
}
